### PR TITLE
adjust the padding to make the bottom line align to right icon

### PR DESCRIPTION
**Pull request by tao12345666333**
When I use the theme, I find the bottom line is not align to right social icons.

### CODE REVIEW

**Comment by DeviaVir** [comment]
Hi @tao12345666333, first off: thanks for your PR!

I tested it out, but I'm wondering how this is now aligned? Were you trying to align it with the bottom?
screen shot 2015-07-29 at 15 07 47

**Comment by tao12345666333** [comment]
Hi my test is here:

before:
2015-08-22-004545_790x102_scrot

2015-08-22-004612_777x67_scrot

after:
2015-08-22-004640_752x90_scrot

2015-08-22-004656_756x55_scrot

**Comment by tao12345666333** [comment]
And I realized that perhaps my fix just adapt to my cases but not general. Thanks for your theme!

**Comment by DeviaVir** [comment]
:+1: thanks, anyway!

**Pull request closed without merging**
